### ISSUE TITLE
Add new team members to Team page

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#101]
@tonyfast, @kcpevey and @ppwadhwa have started contributing to HoloViz on a regular basis. I think that falls under Labs activities, and we should add you all to https://labs.quansight.org/team/ - does that sound interesting and do you want to be added?

cc @dharhas

**Comment by kcpevey** [comment]
I'd love to be added :)

**Comment by rgommers** [comment]
@steff456 of the website issues, this would be my highest prio one. @kcpevey and @tonyfast have indicated they'd like to be added, and they are already contributing to Labs with blog posts. 

Could you work on this? See gh-74 for a similar PR. You can get the Kim's Bamboo photo from Madison or Rebecca. Tony seems to be one of the few people without a photo in Bamboo, so you'll have to make him give you a suitable one.

**Comment by ppwadhwa** [comment]
@rgommers I am sorry I never responded before!  I'd like to be added as well.

**Comment by rgommers** [comment]
Thanks @ppwadhwa! You're in:)

Maybe you should band together for a Holoviews blog post at some point, I'd love to hear about what you're all contributing to it.
