### ISSUE TITLE
Site doesn't build properly for me

### ISSUE THREAD

**Issue by asmeurer** [Quansight-Labs/quansight-labs-site#103]
This is what the site looks like for me when I build it. 
<img width="1612" alt="Screen Shot 2020-07-27 at 12 29 11 PM" src="https://user-images.githubusercontent.com/71486/88577770-c910f600-d004-11ea-9b6b-3e3d00d61dd6.png">

**Comment by asmeurer** [comment]
Seems to render correctly in firefox.

**Comment by asmeurer** [comment]
Just did a reload in Chrome and now it renders fine too. Maybe there was a caching issue.

**Comment by melissawm** [comment]
Is this still relevant?
