### ISSUE TITLE
Add urls for the projects in Team page

### ISSUE THREAD

**Issue by vfdev-5** [Quansight-Labs/quansight-labs-site#107]
A small comment about the Team page and the projects on which a member is working. Can we add an url link to either project official site or the description in https://labs.quansight.org/projects/
For example,
```
Hameer Abbasi
[PHOTO]
[NumPy](github numpy or numpy official docs)
[PyData/Sparse](...)
[uarray](...)
```

cc @rgommers

**Comment by rgommers** [comment]
Thanks @vfdev-5. I agree, that's be good. I think I prefer updating the description at https://labs.quansight.org/projects/ to say what we do for a project rather than just what a project is about, and then linking to that.

**Comment by vfdev-5** [comment]
OK for me.
