### ISSUE TITLE
Blockquote hard to read in Blog

### ISSUE THREAD

**Issue by Carreau** [Quansight-Labs/quansight-labs-site#111]
![Screen Shot 2020-08-05 at 16 04 54](https://user-images.githubusercontent.com/335567/89472492-71c20280-d735-11ea-80dd-e92b41d7630d.png)

Seem to my poor eyes that font-weight:300 is way to thin.

**Comment by rgommers** [comment]
All fonts need to be increased in size, and if that doesn't fix it then the weight can be tweaked too

**Comment by asmeurer** [comment]
Related to #109 IMO
