### ISSUE TITLE
Add search bar and calendar/tags/authors side panel for blog posts

### ISSUE THREAD

**Issue by vfdev-5** [Quansight-Labs/quansight-labs-site#119]
For a more friendly UX, it would be nice to add some of those things : 
- search bar
- sidebar with years (2019, 2020) to easily navigate through the content
- optionally, a sidebar with all tags, all authors to easily navigate through the content by clicking on item and filtering the content...

What do you think ?

**Comment by rgommers** [comment]
Yes I agree, we have quite a bit of content by now, and it'd be good to have a better way of surfacing it. 

The search bar would be my number one wish; a sidebar on the blog pages also makes sense to me.

**Comment by mattip** [comment]
For search there is a [plugin builtin to nikola](https://github.com/getnikola/plugins/tree/master/v7/localsearch), it uses a javascript local solution. The link to the source of the search and docs lead to [Tipue Search](http://www.tipue.com/search/), which is broken but maybe it JustWorks(tm)?

**Comment by vfdev-5** [comment]
How about that : https://github.com/getnikola/nikola/commit/16ade9c5db0fa5b8393cab283eef31e766ee915f ?

**Comment by asmeurer** [comment]
I never got the local search thing to work on my own Nikola blog. If we can, that would be great.

**Comment by mattip** [comment]
Search is now working. There is a Nikola plugin called [sidebar](https://plugins.getnikola.com/v7/sidebar/), [here](https://www.pypy.org/blog/) is how it looks on the PyPy blog. Before that I would add the various indices to the blog menu item on the top navbar: compare this site's top menu to PyPys to see what I mean.

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
