### ISSUE TITLE
add Gregory Lee to team page

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#142]
Hi @steff456, can you also add Greg to the team page?

Cc @grlee77 - it's this page, where we put everyone and the projects they work on: https://labs.quansight.org/team/. I think for you it's:
- scikit-image
- SciPy
- PyWavelets
- CuPy
?

**Comment by grlee77** [comment]
Those are definitely the key four to include, I think. Another project where I have merge rights and have managed releases is pyFFTW, but I will leave it up to you if you prefer to list it or not. I haven't done much there recently and it is mostly in maintenance mode.

**Comment by rgommers** [comment]
I'd say why not, let's include it. At least if it doesn't screw up formatting too much (if so, please leave it out @steff456).

**Comment by grlee77** [comment]
Also, although I am a frequent CuPy contributor, I am not officially a maintainer for the package. I think all of the people with merge rights are Preferred Networks employees.

**Comment by rgommers** [comment]
True. CuPy is a project that feels like a community project, but isn't. Technically we shouldn't list it here. It's in an interesting state.

You don't have to have commit rights to be listed here, structural contributions is what matters. Let's leave it on. In a similar state as Numba I'd say, which we also list.

**Comment by grlee77** [comment]
just checking in here, @steff456 . I think the consensus above was to list:

- scikit-image
- SciPy
- PyWavelets
- CuPy
- PyFFTW

**Comment by steff456** [comment]
Thanks @grlee77!
