### ISSUE TITLE
Add Quansight Labs logo files to this repo

### ISSUE THREAD

**Issue by asmeurer** [Quansight-Labs/quansight-labs-site#163]
Can we add the Quansight Labs logo files to this repo (specifically the gh-pages), so that I can link it from the README? Right now the old logo is there, but the only version of the new logo is one that can't be used against a white background.

**Comment by rgommers** [comment]
Done @asmeurer, there's now color versions in both rectangular and square format in `files/images/`

**Comment by asmeurer** [comment]
Thanks. I plan to link to the version on the site in the ndindex README and docs.
