### ISSUE TITLE
Code blocks are a little difficult to read

### ISSUE THREAD

**Issue by kurtamohler** [Quansight-Labs/quansight-labs-site#176]
For me, the black text on gray code blocks are a bit hard to read. Comments in code, which are a very light blue, are even harder. Does anyone else have this problem?

For example, the third code block on this page: https://labs.quansight.org/blog/2020/04/pytorch-tensoriterator-internals/

I think these two changes could make it easier on the eyes:

- Change the gray code block background to either match the white background, or make it a much lighter gray
- Darken or brighten the comment text color

**Comment by rgommers** [comment]
It personally doesn't bother me, but I agree this can and should be improved. Thanks for the report @kurtamohler
