### ISSUE TITLE
remove Makefile and handle localsearch dependency better

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#178]
See https://github.com/Quansight-Labs/quansight-labs-site/pull/167/files#r610653619 for details. @mattip would you be able to take care of this?

**Comment by mattip** [comment]
> Invoking pip install and downloading packages on every invocation of make auto is a big no-no. 

My goals were:
- abstract the preview build to allow configuring it from the repo (`nikola build` was too limited)
- abstract the local build to ensure plugins and virtualenv are set up properly

If the Makefile is unacceptable, what would be a better strategy? Or is the problem the lack of caching?

**Comment by rgommers** [comment]
@asmeurer already pointed out the solution in the linked comment, just commit whatever is downloaded now.

We do not want virtualenvs set up (this is bad UX in general and especially with conda), and no abstraction seems to be needed. If you want to make life easier for virtualenv users, the standard approach is to just add a `requirements.txt` file - which is already present in the repo.
