### ISSUE TITLE
Comments boxes? 

### ISSUE THREAD

**Issue by asmeurer** [Quansight-Labs/quansight-labs-site#18]
Can we add comments boxes to the bottom of the posts?

**Comment by rgommers** [comment]
I guess so. Just adding Discus?

**Comment by asmeurer** [comment]
Yeah, I don't know any better options. It's pretty easy to add to Nikola, from what I remember.

**Comment by Carreau** [comment]
https://utteranc.es/ ? That literally use github issues as a storing backend.

**Comment by asmeurer** [comment]
Travis mentioned it on Slack a long time ago as an option for the labs blog. I still want to add it to my own blog to see how well it works.

**Comment by asmeurer** [comment]
I have added support for Utterances in Nikola https://github.com/getnikola/nikola/pull/3459. As soon as that gets in a release, it should be easy to add it.

**Comment by mattip** [comment]
nice!

**Comment by asmeurer** [comment]
Nikola 8.1.2 was just released with support for Utterances.

**Comment by Carreau** [comment]
See #223
