### ISSUE TITLE
Use Lektor from PyPI or conda-forge

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/quansight-labs-site#2]
Lektor is available on [PyPI](https://pypi.org/project/Lektor/) and [conda-forge](https://anaconda.org/conda-forge/lektor) as a noarch package. It's also up-to-date. Should we be using this instead of the Linux-ish installer script as a more cross-platform alternative? I tested `master` and it works fine with the conda-forge version.

If this is something we want, I can send a PR to `master` to update the `README`.

**Comment by rgommers** [comment]
I actually like the weird install method, because I have the `lektor` command always available and I can keep it out of my `base` conda env. On TravisCI it doesn't matter. But yes, would be good to document in `README` that `pip`/`conda` work too.
