### ISSUE TITLE
Onboarding docs did not mention the Labs website

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/quansight-labs-site#203]
When I joined Quansight I was asked to provide a picture for the "About us" page at Quansight.org during onboarding, but it didn't mention the [Team](https://labs.quansight.org/team/) page at labs.quansight.org. Will this feature the same content and we don't have to do anything about it or should we submit a PR to add ourselves to the page?

**Comment by rgommers** [comment]
Thanks for reminding us Jaime! It's been my job to remember that, and I've been busy. We should add it to the Labs handbook.

We need a few changes:
- Remove Hameer Abbasi
- Remove Tim George 
- Add @jaimergp - project conda-forge
- Add @thomasjpfan - project scikit-learn
- Add @czgdp1807 (project SymPy, LFortran, NumPy)

@steff456 would you be able to do this?

**Comment by steff456** [comment]
Sure! I will update the labs team!

**Comment by czgdp1807** [comment]
Thanks @steff456

**Comment by trallard** [comment]
@rgommers  I can add a step to the onboarding process in the handbook to indicate folks need to open a `PR` against this repo to add themselves to the team
