### ISSUE TITLE
Add indexing by date and tag

### ISSUE THREAD

**Issue by mattip** [Quansight-Labs/quansight-labs-site#204]
Nikola makes available indexing blog posts by [dates](https://labs.quansight.org/archive.html) and [tags (categories)](https://labs.quansight.org/categories/).  These can be exposed for better discoverability, but someone needs to think about how. Submenu from the Blog item? Somewhere new? Also is the tags formatting what we want (why is JLabA11y special)?

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
