### ISSUE TITLE
pyinotify is not available for MacOSX

### ISSUE THREAD

**Issue by vfdev-5** [Quansight-Labs/quansight-labs-site#207]
Following README and `pip install -r requirements.txt` fails to install pyinotify:
```
    Complete output (1 lines):
    inotify is not available on macosx-10.9-x86_64
```
even if my mac if later than 10.9...

**Comment by rgommers** [comment]
I could swear this used to work, but `pyinotify` is Linux-only says https://pypi.org/project/pyinotify/ and hasn't changed since 2015. So this broke the first time I changed `requirements.txt` to use the output of `pip freeze`.

This was an expensive issue to investigate ... https://twitter.com/ralfgommers/status/1404686514248953859

**Comment by rgommers** [comment]
Removing `pyinotify` from `requirements.txt` completely may fix it?

**Comment by rgommers** [comment]
Guess we should join the cool crowd, and replace `requirements.txt` with https://github.com/pypa/pipfile. And use unpinned deps for development, and a separate `Pipfile.lock` for CI.

Having this many dependencies for a website framework kind of sucks.

**Comment by vfdev-5** [comment]
> This was an expensive issue to investigate ... https://twitter.com/ralfgommers/status/1404686514248953859

That's why I prefer to have conda in docker containers. Just restart it and that's it :)

> Removing pyinotify from requirements.txt completely may fix it?

Yes, I removed it locally and could started building the site. I had don't know why another issue with missing "gonzalo_peña.jpg" file and the website was built with blogs up to 10/2020. Tweaking something I could solve the issue and build everything...

**Comment by trallard** [comment]
closing as this was sorted by Matthias
