### ISSUE TITLE
Projects page needs an update

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#209]
Projects we need to add because we're making active contributions in a significant way:
- scikit-learn
- scikit-image
- IPython
- Napari
- Cython
- Pandas
- stdlib.js
- Elegy

Projects that should move to a new "archived" (think of a better name) category:
- XND
- metadsl

Projects we're not currently contributing much to but would like to ramp up again (so should be moved to "want to support" category):
- Dask
- Holoviz

**Comment by rgommers** [comment]
Hi @juanis2112, this would probably be a good thing to prioritize - the Projects page is pretty badly out of date. The descriptions of _what_ we do per project is a larger undertaking, but getting the names and logos right should be a quick fix.

**Comment by juanis2112** [comment]
Yeap, this week I will be working on PRs to fix this :)

**Comment by juanis2112** [comment]
From your list:  I think Consortium for Python Data API Standards is also missing. Should I include it?

**Comment by rgommers** [comment]
Good catch - yes please!
