### ISSUE TITLE
Transfer Netlify ownership

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/quansight-labs-site#216]
Right now we are on the free Netlify plan which means only one person can have access to the project. 

TO DO: change ownership to Tania or Ralf

**Comment by Carreau** [comment]
I don't know if it's worth looking into cloudflare pages, which is similar.

**Comment by Carreau** [comment]
https://bejamas.io/compare/netlify-vs-cloudflare-pages/ it looks like cloudflare pages covers all we used in netlify and allows up to 5 managers. 

I have not used it before  but was curious about it.

**Comment by Carreau** [comment]
And 30 minutes later, I have it setup on my fork, pretty straitforward to try.

Here is a PR against my fork that also build it. It's a tad slower and a bit less intuitive than netlify, but cloudflare products are usually quite good. If we use it for other things it's worth considering IMHO. I'm happy to invite anybody interested to my fork/account to try it.

We can also deploy it here for previews concurrently to netlify to try it for pull-requests. Main issues would be migrating DNS/nameservers.

**Comment by Carreau** [comment]
You could have told me I did not [link to the PR](https://github.com/Carreau/quansight-labs-site/pull/3) !

**Comment by Carreau** [comment]
See https://quansight.slack.com/archives/C8XHBCE8L/p1626541869257800 for a discussion as to how to handle cloudflare internally.
