### ISSUE TITLE
[DISCUSS] - do we need RSS in our new site?

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/quansight-labs-site#328]
We currently have RSS is this something we want to carry over? cc/ @rgommers

**Comment by rgommers** [comment]
Meh .... only if it comes for (almost) free with the blogging solution we use I'd say. Which I expect is the case (I've never seen a blogging solution not have builtin support)? We do use it to syndicate to planet.scipy.org/ and https://www.planetpython.org/.

**Comment by trallard** [comment]
Will follow up with Naturaily this week

**Comment by mattip** [comment]
+1 for RSS, it is the way blog posts show up in my feed (thunderbird mail client)
