### ISSUE TITLE
Add a PR preview method

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#4]
Otherwise things will break too easily.

GitHub Pages doesn't allow serving both from `master` and `gh-pages`, so perhaps easiest to switch to CircleCI which will store build artifacts and will render the whole site correctly in its UI.

**Comment by hameerabbasi** [comment]
There's Azure Pipelines artifacts as well... I can set that up if it's needed.

**Comment by rgommers** [comment]
Okay I haven't used that yet. Am very happy with Azure Pipelines CI robustness and speed though. Would you prefer it over CircleCI? If so, then setting that up would be much appreciated!

**Comment by hameerabbasi** [comment]
The downside is that artifacts aren't public. The upside is speed and number of runners. :) It's your decision, I can set either up.

**Comment by rgommers** [comment]
Given that on Azure we can only add 5 people, most blog authors won't be able to preview. So I'd say let's go with CircleCI. Speed won't be much of an issue, CircleCI has been pretty good.

**Comment by rgommers** [comment]
Interesting, thanks @costrouc. I'd be tempted to try that sometime, but perhaps on a repo where we need the extra capabilities (python-moa, xnd, uarray, ...). This site is pretty basic and doesn't require much in terms of resources.
