### ISSUE TITLE
Post/Blog navigation inconsistency

### ISSUE THREAD

**Issue by koliphan2** [Quansight-Labs/quansight-labs-site#63]
There is an inconsistency in how we currently navigate through the blog posts. On the blog page, where there are snippets of different posts, it has New on the left, Old on the right.
<img width="935" alt="Screen Shot 2020-03-14 at 4 18 41 PM" src="https://user-images.githubusercontent.com/35544523/76690610-a363f100-660f-11ea-85b5-cae17f111445.png">

When we click into an actual post, it is opposite, where Previous is on the left, and Next is on the right.
<img width="900" alt="Screen Shot 2020-03-14 at 4 19 07 PM" src="https://user-images.githubusercontent.com/35544523/76690612-a4951e00-660f-11ea-9522-2b15e3bbcce6.png">
If the previous post is older, shouldn't it match positionally as well?

Also, do we want a link to the archive of blog posts available? It could be placed as shown in the later image example in between the two navigation links.

**Comment by rgommers** [comment]
Yes indeed, that's inconsistent. To me, keeping the right side as going forward in time would be more natural. So "Newer posts" / "Older posts" could be switched around.

I think that's built into Nikola. @koliphan2 maybe you could see if there's an existing Nikola bug report for this?

**Comment by koliphan2** [comment]
With Nikola, they have the built in templates yes, but they also allow you to basically move those default files into your project and edit them for small changes. For big ones, you normally create new templates like we have, but I've also edited some built in ones for the smaller changes too. 

It was mainly an issue of figuring out which way we should have it. I think I know how to solve it, but will also make a report if it ends up not sticking or removing itself later.

**Comment by koliphan2** [comment]
Also, just as I'm looking at this, would we want the navigation available both top and bottom? Or just keep it at the bottom?

**Comment by rgommers** [comment]
I think just the bottom. Okay, overwriting the defaults sounds good to me:)

**Comment by koliphan2** [comment]
Just fixed it and pushed it to NewSite!

**Comment by rgommers** [comment]
Thanks @koliphan2:) For the next ones, can you try to submit PRs instead?
