### ISSUE TITLE
Design Ideas

### ISSUE THREAD

**Issue by koliphan2** [Quansight-Labs/quansight-labs-site#65]
With the site, two major things stand out to me that we need to figure out, and they will affect every page. 

1: Dark or light Header?
2: Dark or light body?

Most pages will follow that same format, so I've made demos of the 'team' page with a different combination of header and body. Along side that, there are two different ideas with how the team page could look as well, but that would just be specific to this page. 

You're seeing a lot of purple to keep it based around our logo. I think it'd also be good to place some orange or green highlights, though those are still up in the air as to if and where.

The top row is the circles we've said we liked, and the bottom follows more along the lines of the Quansight 'about' page. As a sister site, I thought it might be good to have some harmony between the two websites. 

Thoughts?

![Options](https://user-images.githubusercontent.com/35544523/77591795-b8b60680-6ebe-11ea-899b-4b93643f3e50.jpg)

**Comment by rgommers** [comment]
Oh, hard choices ....

Thanks @koliphan2, good questions/suggestions. I find it hard to choose based on aesthetics alone. I do think though that a white background is much easier to work with on many pages; if this page would have a purple background then what do we do with a blog - code, images, etc. would all look weird. 

I do like some color, so the purple header/footer (col 3) is preferable over the all-white (col 2). Also like the fonts and all-white logo there better.

So I'd vote for the third column, with little preference for round or square photos.

@dalthviz any thoughts? 

Also pinging @MarsBarLee for a more informed design opinion.

**Comment by dalthviz** [comment]
* +1 in making the header/footer purple (and in general following the aesthetics of the header/footer of the [Quansight site](https://www.quansight.com) ).
* I like the circle images more (and it looks even better with the overlapping of the GitHub logo in the images as shown in the mockup).

**Comment by MarsBarLee** [comment]
For me, I generally prefer white background with purple header/footer, so column 3 from me as well. I like the circle photos as well, since it establishes a visual identity separate from the main Quansight site. Quansight Lab has circles vs the squares of the Quansight website. I also prefer the font and layout of the circle photos.

I also really the all-white logo for header, rather than the all-color logo. 

I feel like purple on purple is too heavy. Same color background + header sites are very 'in' right now but it is more bold look, and I feel comes off too strong with the dark purple.

I personally like the white on white, but I think it might be too much of a departure from the Quansight site, as a sister site.

I don't have much an opinion of purple background with white background but I can see what Ralf is saying about the purple background making difficulties with content. It does require one to be more deliberate with how the content will be laid out, and that would be more work than we want.

**Comment by koliphan2** [comment]
With the 3rd column in mind, I'm going to do mock-ups of the other main pages. This one is the blog page, with the details then also going into the individual post pages such as title, tag, and link color.

Links, Title, Author, and Tags all the same color (This is the highlight color, but we can also do the base purple color) 
<img width="475" alt="Screen Shot 2020-03-31 at 12 16 24 PM" src="https://user-images.githubusercontent.com/35544523/78057747-d6ff8480-734c-11ea-939d-bc8f18143a79.png">

Links, Title, and Author all the same color, with Tags remaining grey. (Could be highlight green color or we could stick with purple.
<img width="475" alt="Screen Shot 2020-03-31 at 12 17 12 PM" src="https://user-images.githubusercontent.com/35544523/78057752-d961de80-734c-11ea-8234-fe78dece57a1.png">

Links, Author, (potentially tags) all the same color, with Black titles (and maybe grey tags). These can also be in highlight or the base purple.
<img width="475" alt="Screen Shot 2020-03-31 at 12 22 48 PM" src="https://user-images.githubusercontent.com/35544523/78057754-d9fa7500-734c-11ea-96b8-8bffffc78cce.png">

With any of these, if one aspect stands out as good looking, and another from another image, we can mix and match, ie Grey Tags with the Title/Link/Author in the highlight green. These are just the kind of elements that I've come across as the main design elements of the page that we focus on. Please offer any changes or ideas you have as well.

**Comment by rgommers** [comment]
Nice @koliphan2. My $2c: not a huge fan of green text, I'd go for grey labels, purple names and links, and either purple or black titles.

**Comment by koliphan2** [comment]
Here is kind of what I've got. I'm draw to the green because I think it's nice to have the dual color, but it's up for change if we want. The wording is also changed as I tried making them sound less repetitive.

<img width="381" alt="Screen Shot 2020-04-02 at 2 43 12 PM" src="https://user-images.githubusercontent.com/35544523/78294877-b7a15c80-74f0-11ea-8772-4dd01aaef79d.png">
<img width="381" alt="Screen Shot 2020-04-02 at 2 44 27 PM" src="https://user-images.githubusercontent.com/35544523/78294879-b839f300-74f0-11ea-8bb0-0552b695481f.png">
<img width="381" alt="Screen Shot 2020-04-02 at 2 46 09 PM" src="https://user-images.githubusercontent.com/35544523/78294935-d7d11b80-74f0-11ea-9938-8903050b5baf.png">

**Comment by mattip** [comment]
Is this issue about https://labs.quansight.org ? I don't see a "teams" tab on the header at all right now, in fact that site looks rather minimal.

**Comment by dalthviz** [comment]
Hi @mattip the changes for the website haven't been merged with master yet (so the deployed site currently doesn't show for example the team page).

The branch with the changes (and the team page) is `newsite` and there is a WIP PR implementing the style changes described here (#75)

Hope that this makes more clear the state of website :)

**Comment by mattip** [comment]
Yes thanks, makes sense. Hope it can move forward soon

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
