### ISSUE TITLE
Add build preview on PRs

### ISSUE THREAD

**Issue by goanpeca** [Quansight-Labs/quansight-labs-site#83]
Adding build previews with Netlify would provide precise of the site on every PR (free for open source).

It is relatively straight forward to do. 

See steps to similar workflow here: https://github.com/beeware/beeware.github.io/pull/426

**Comment by rgommers** [comment]
Thanks Gonzalo, sounds useful. A PR would be great.

**Comment by goanpeca** [comment]
Will do.

**Comment by goanpeca** [comment]
It seems I need some sort of write permissions to be able to enable this on netlify.

**Comment by rgommers** [comment]
sent you an invite with `miaintain` permissions
