### ISSUE TITLE
netlify integration is broken

### ISSUE THREAD

**Issue by mattip** [Quansight-Labs/quansight-labs-site#92]
It should use requirements.txt to install dependencies.

**Comment by goanpeca** [comment]
Hi @mattip what do you mean?

**Comment by mattip** [comment]
The netlify integration is failing on PRs like #91. It seems it cannot find nikola.

**Comment by goanpeca** [comment]
Yes, just noticed. That is weird, it was working hmmm will have to take a look :-)

**Comment by mattip** [comment]
Maybe because this is based off an older master without the requirements.txt?

**Comment by goanpeca** [comment]
Yes, that is possible. A rebase/merge with `master` should fix it then.

**Comment by mattip** [comment]
OK, closing then. Sorry for the bother.
