### ISSUE TITLE
Improve logo sizes on Projects page

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#98]
Some of the logos (e.g. JupyterLab) take up too much vertical space on https://labs.quansight.org/projects/, this should be fixed so there's a better balance between logo sizes and vertical whitespace in the text column next to it.

**Comment by Carreau** [comment]
Dask and conda-forge logo in particular seem to be really low res.

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
