### ISSUE TITLE
Create a graphical element for the front page

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/quansight-labs-site#99]
The front page at https://labs.quansight.org/ is too sparse now. The only graphical elements are the sponsor logos. I'd like to have a banner or other graphic near the top. One option I thought of was a variant of the world map with dots for locations of team members that we had on the doors of the cabins for the retreat. @tonyfast what we you think? or any other ideas?

**Comment by trallard** [comment]
Closing since this will no longer be applicable with the website migration 🚀
